#pragma once
#include <Windows.h>
#include "../glew.h"
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <string>
#include <sstream>
#include <vector>
#include <functional>
#include <map>
#include "../external/Glm/glm.hpp"
#include "../external/Glm/ext.hpp"